activity-monitors:
  - max-activity-time: 5m
    inactivity-time: 30s
    message-format: You worked for %s already! Let your eyes rest for a bit.
  - max-activity-time: 30m
    inactivity-time: 1m
    message-format: You worked for %s already! Go take a walk.

